- alias: "Set LED Color Based on Distance"
  trigger:
    platform: numeric_state
    entity_id: sensor.parking_distance
    below: 10
  action:
    service: mqtt.publish
    data_template:
      topic: "garage/parking/led/set"
      payload: >
        {
          "state": "ON",
          "color": {"r": 255, "g": 0, "b": 0},
          "brightness": {{ states('input_number.led_brightness') | int }}
        }

- alias: "Set LED Color to Green for Safe Distance"
  trigger:
    platform: numeric_state
    entity_id: sensor.parking_distance
    above: 20
  action:
    service: mqtt.publish
    data_template:
      topic: "garage/parking/led/set"
      payload: >
        {
          "state": "ON",
          "color": {"r": 0, "g": 255, "b": 0},
          "brightness": {{ states('input_number.led_brightness') | int }}
        }

- alias: "Set LED Color to Orange for Caution Zone"
  trigger:
    platform: numeric_state
    entity_id: sensor.parking_distance
    below: 20
    above: 10
  action:
    service: mqtt.publish
    data_template:
      topic: "garage/parking/led/set"
      payload: >
        {
          "state": "ON",
          "color": {"r": 255, "g": 165, "b": 0},
          "brightness": {{ states('input_number.led_brightness') | int }}
        }

- alias: "Send distance thresholds and brightness to Raspberry Pi"
  trigger:
    - platform: state
      entity_id:
        - input_number.red_distance_threshold
        - input_number.orange_distance_threshold
        - input_number.led_brightness
        - input_boolean.parking_system_enabled
  action:
    service: mqtt.publish
    data_template:
      topic: "garage/parking/settings"
      payload: >
        {
          "red_distance_threshold": {{ states('input_number.red_distance_threshold') | int }},
          "orange_distance_threshold": {{ states('input_number.orange_distance_threshold') | int }},
          "brightness": {{ states('input_number.led_brightness') | int }},
          "enabled": {{ (states('input_boolean.parking_system_enabled') == 'on') | string | lower }}
        }

- alias: "Send Settings on Request"
  trigger:
    platform: mqtt
    topic: "garage/parking/settings/get"
  action:
    service: mqtt.publish
    data_template:
      topic: "garage/parking/settings"
      payload: >
        {
          "red_distance_threshold": {{ states('input_number.red_distance_threshold') | int }},
          "orange_distance_threshold": {{ states('input_number.orange_distance_threshold') | int }},
          "brightness": {{ states('input_number.led_brightness') | int }},
          "enabled": {{ (states('input_boolean.parking_system_enabled') == 'on') | string | lower }}
        }
