mobile_app:
mqtt:
  sensor:
    - name: "Parking Distance"
      state_topic: "garage/parking/distance"
      unit_of_measurement: "cm"
      value_template: "{{ value | float | round(2) }}"

input_number:
  red_distance_threshold:
    name: "Red Distance Threshold"
    initial: 10
    min: 1
    max: 100
    step: 1

  orange_distance_threshold:
    name: "Orange Distance Threshold"
    initial: 20
    min: 1
    max: 100
    step: 1

  led_brightness:
    name: "LED Brightness"
    initial: 20
    min: 0
    max: 255
    step: 5

input_boolean:
  parking_system_enabled:
    name: "Parking System Enabled"
    initial: true

automation: !include automations.yaml