# configuration.yaml

# Enable Mobile App Integration
mobile_app:

# MQTT Integration
mqtt:

# Sensors
  sensor:
    - name: "Front Parking Distance"
      state_topic: "garage/parking/distance/front"
      unit_of_measurement: "cm"
      value_template: "{{ value | float | round(2) }}"
      unique_id: "sensor_parking_distance_front"
  
    - name: "Left Parking Distance"
      state_topic: "garage/parking/distance/left"
      unit_of_measurement: "cm"
      value_template: "{{ value | float | round(2) }}"
      unique_id: "sensor_parking_distance_left"
  
    - name: "Right Parking Distance"
      state_topic: "garage/parking/distance/right"
      unit_of_measurement: "cm"
      value_template: "{{ value | float | round(2) }}"
      unique_id: "sensor_parking_distance_right"

# Input Numbers (for Thresholds and Brightness)
input_number:
  red_distance_threshold_front:
    name: "Red Distance Threshold Front"
    initial: 10
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  orange_distance_threshold_front:
    name: "Orange Distance Threshold Front"
    initial: 20
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  red_distance_threshold_left:
    name: "Red Distance Threshold Left"
    initial: 10
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  orange_distance_threshold_left:
    name: "Orange Distance Threshold Left"
    initial: 20
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  red_distance_threshold_right:
    name: "Red Distance Threshold Right"
    initial: 10
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  orange_distance_threshold_right:
    name: "Orange Distance Threshold Right"
    initial: 20
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  led_brightness:
    name: "LED Brightness"
    initial: 20
    min: 0
    max: 255
    step: 5
    mode: slider
    icon: "mdi:brightness-6"

# Input Boolean (for System Enable/Disable)
input_boolean:
  parking_system_enabled:
    name: "Parking System Enabled"
    initial: true
    icon: "mdi:garage"

# Include Automations from a Separate File
automation: !include automations.yaml
