# configuration.yaml

# Enable Mobile App Integration
mobile_app:

# MQTT Integration
mqtt:

# Sensors
  sensor:
    - name: "Front Parking Distance"
      state_topic: "garage/parking/sensor/front/distance"
      unit_of_measurement: "cm"
      value_template: "{{ value | float | round(2) }}"
      unique_id: "sensor_parking_distance_front"

    - name: "Left Parking Distance"
      state_topic: "garage/parking/sensor/left/distance"
      unit_of_measurement: "cm"
      value_template: "{{ value | float | round(2) }}"
      unique_id: "sensor_parking_distance_left"

    - name: "Right Parking Distance"
      state_topic: "garage/parking/sensor/right/distance"
      unit_of_measurement: "cm"
      value_template: "{{ value | float | round(2) }}"
      unique_id: "sensor_parking_distance_right"

    - name: "AI Obstacle Detection"
      state_topic: "garage/parking/ai_detection"
      value_template: "{{ value }}"
      icon: "mdi:car-brake-alert"
      unique_id: "sensor_ai_obstacle_detection"
    
    - name: "Garage Process State"
      state_topic: "garage/parking/process_state"
      icon: "mdi:garage"
      unique_id: "sensor_garage_process_state"
      
# Cover
  cover:
    - name: "Garage Door"
      command_topic: "garage/parking/garage_door/command"
      state_topic: "garage/parking/garage_door/state"
      payload_open: "OPEN"
      payload_close: "CLOSE"
      state_open: "OPEN"
      state_closed: "CLOSE"
      optimistic: false
      qos: 0
      retain: false
      icon: "mdi:garage"

# Input Numbers (for Thresholds and Brightness)
input_number:
  red_distance_threshold_front:
    name: "Red Distance Threshold Front"
    initial: 3
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  orange_distance_threshold_front:
    name: "Orange Distance Threshold Front"
    initial: 10
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  red_distance_threshold_left:
    name: "Red Distance Threshold Left"
    initial: 3
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  orange_distance_threshold_left:
    name: "Orange Distance Threshold Left"
    initial: 10
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  red_distance_threshold_right:
    name: "Red Distance Threshold Right"
    initial: 3
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  orange_distance_threshold_right:
    name: "Orange Distance Threshold Right"
    initial: 10
    min: 1
    max: 100
    step: 1
    mode: box
    icon: "mdi:map-marker-distance"

  led_brightness:
    name: "LED Brightness"
    initial: 20
    min: 0
    max: 255
    step: 5
    mode: slider
    icon: "mdi:brightness-6"

# Input Boolean (for System Enable/Disable)
input_boolean:
  parking_system_enabled:
    name: "Parking System Enabled"
    initial: true
    icon: "mdi:garage"

# Include Automations from a Separate File
automation: !include automations.yaml
